### ISSUE TITLE
Its throwing an error

### ISSUE THREAD

**Issue by baltechies** [tinify/tinify-php#11]
Fatal error: Uncaught exception 'Tinify\ClientException' with message 'Server responded with 403 (HTTP 400/Source not found)' in *****/tinify-php-master/lib/Tinify/Exception.php on line 18

Tinify\ClientException: Server responded with 403 (HTTP 400/Source not found) in *****/tinify-php-master/lib/Tinify/Exception.php on line 18

**Comment by rolftimmermans** [comment]
Hi! Could you post your code please?

**Comment by baltechies** [comment]
Following is the code. I have replaced by API Key and URL of Image

require_once("vendor/autoload.php");
\Tinify\setKey("API-KEY"); 
$source = \Tinify\fromUrl("URL OF IMAGE");
$source->toFile("dummy.png");

Or

require_once("vendor/autoload.php");
\Tinify\setKey("API-KEY"); 
$source = \Tinify\fromFile("test/examples/dummy.png");
$source->toFile("dummy.png");

**Comment by baltechies** [comment]
PFA. May be this terminal screenshot helpful.
![screen shot 2016-06-17 at 1 19 13 pm](https://cloud.githubusercontent.com/assets/13519944/16144067/564dd25c-348e-11e6-963b-7053849a16b0.png)

**Comment by rolftimmermans** [comment]
Thanks for posting your code. This error is thrown because you use `fromUrl`. This reaches out to server where the image is hosted and attempts to fetch and optimise it. 

The server that hosts the image is responding with an `HTTP 403` error, however. That is what `Server responded with 403` means.

This could be due to a variety of reasons. If you request the image URL with a web browser, does that work? What about if you use a tool like curl (`curl <image url>` from the command line)?

**Comment by baltechies** [comment]
Hi,
I have used https://upload.wikimedia.org/wikipedia/commons/1/1e/Stonehenge.jpg as image url. Then its throwing following error.

![2016-06-17 16-24-59](https://cloud.githubusercontent.com/assets/13519944/16148580/2ac9f128-34a8-11e6-8efd-e6a8f75cdf23.png)


Code is:

require_once("vendor/autoload.php");
\Tinify\setKey("HDpFOvEGjy95j1b4ZYqLOA5BrqwKdoao");
$source = \Tinify\fromUrl("https://upload.wikimedia.org/wikipedia/commons/1/1e/Stonehenge.jpg");
$source->toFile("/Users/balvinderSingh/Sites/tinify-php-master/dummy.jpg");

**Comment by rolftimmermans** [comment]
The error `name lookup timed out` could indicate that there is a problem with your DNS server or your network connection. Can you attempt any network requests from your server? To other URLs, or maybe with `curl` directly from your server?

**Comment by baltechies** [comment]
@rolftimmermans  Great! Thank You very much. Its working.
I have switched my network, then its working fine.
