### ISSUE TITLE
Set image headers on S3 upload

### ISSUE THREAD

**Issue by tr33m4n** [tinify/tinify-php#12]
Hi there,

I was wondering whether there was a way of setting a header with the image upload to S3? For example, setting a "has-been-tinyfied" header on the image would be handy if using the library for more complex projects

Cheers

**Comment by rolftimmermans** [comment]
Hi,

At the moment this is not possible. The easiest would be to add extra data after the `store()` method returns. At that moment the compressed file should be present in S3. 

It's an interesting feature though, and we'll consider adding this to our API.

**Comment by thomasjsn** [comment]
+1

I am looking for a way to set `Cache-Control` headers; something like:

```
"headers" => array(
    "Cache-Control" => "max-age=31536000,public" // 1 year
),
```

On the `store` method perhaps?

**Comment by michielverkoijen** [comment]
Custom header support by the Tinify API is planned later this month (October 2018). If updates to the clients are needed this will likely follow after that improvement.

**Comment by rkoopmans** [comment]
Closing this, as this feature is available. See the documentation here: https://tinypng.com/developers/reference/php
