### ISSUE TITLE
Add padding to resized image

### ISSUE THREAD

**Issue by eytanchen** [tinify/tinify-php#17]
It would be great to be able to pass a top-bottom left-right padding value (by pixels or percent maybe), to be added around the image when resizing it, and also the HEX color value to fill the padded area.

**Comment by rolftimmermans** [comment]
Hi! Thanks for sharing your idea. We are working on some improvements on our resizing API and wonder if you could share more details about your use case with support@tinify.com? Maybe we can invite you to do some beta testing. Thanks!

**Comment by michielverkoijen** [comment]
We have created a new `thumb` mode for resizing. This detects free standing objects and will add padding on the left-right or top-bottom. Is this maybe useful for your resizing, or do you have a different use-case?
