### ISSUE TITLE
Cover Image create black line in rigth border

### ISSUE THREAD

**Issue by DaviMenezes** [tinify/tinify-php#19]
Im trying cover image with anyting size and the images is returned with a fine black line in the rigth border
See with attention, download the image and open in yours desktop. Thanks
https://i.imgur.com/w5t4aN4.jpg

**Comment by tinify-support** [comment]
Hi DaviMenezes,

We could not find a black line in the image you linked to. 
If you send the original and compressed image to support@tinify.com we can look into this.
