### ISSUE TITLE
lib-curl dependency

### ISSUE THREAD

**Issue by anthonygulin** [tinify/tinify-php#20]
Hi there,

`tinify/tinify 1.5.2 requires lib-curl >=7.20.0 -> the requested linked library curl has the wrong version installed or is missing from your system, make sure to have the extension providing it.`

Does tinify actually require 7.20.0, or could 7.19.0 be run?

Cheers!

**Comment by anthonygulin** [comment]
Use the --ignore-platform-reqs flag.

**Comment by codedesign** [comment]
did you find a solution? I am having the same issue.

**Comment by emielvanlankveld** [comment]
In the past we've seen some issues with 7.19.7 which is why the minimum requirement is set to 7.20.0. Feel free to use the workaround though if you are not experiencing any problems with it.

**Comment by lezabour** [comment]
yes it's good now!
thanks
