### ISSUE TITLE
why php run tinfy-php is very slowly

### ISSUE THREAD

**Issue by a6965921** [tinify/tinify-php#26]
why php run tinfy-php is very slowly

tinfy api not use cdn???

**Comment by rolftimmermans** [comment]
Thanks for your comment! Can you please provide more specifics about what you mean when you say that the API is slow? 

- What kind of images are you optimizing, could you share examples?
- Could you share some logs/timestamps? That would help us pinpoint when exactly you saw slow responses and precisely how long they took.

The API does not use a CDN. Images will only be served back to the user of the API, so distributing them to a CDN does not make much sense. If you're looking at a way to serve your images to your (end) users then you might be interested in [Tinify CDN](https://tinify.com/cdn).

Hopefully this answers your question!
