### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by lahmacun** [tinify/tinify-php#30]
Hello everyone, hope y'all doing well.
Yesterday, I started to getting this error:
```
Uncaught PHP Exception Tinify\ConnectionException: "Error while connecting: SSL certificate problem: certificate has expired (#60)" at /var/www/mywebsite/vendor/tinify/tinify/lib/Tinify/Client.php line 140
Level
CRITICAL
```
Since my project is really old and have a lots of dependencies, I can not run `composer update` command. Then I checked the difference between latest update-cacert.sh and mine. I replaced my update-cacert.sh with the new one and run the command. But I still got the error. What can I do? Is there any ideas?

Best Regards.

**Comment by rkoopmans** [comment]
Hi lahmacun,

You will have to update this file: https://github.com/tinify/tinify-php/blob/master/lib/data/cacert.pem

On 30 September the LetsEncrypt root certificate expired which is used for validating the integrity of a secure connection to the tinify API service.

On most systems, this is not a problem because our certificates are cross signed and we include both the ISRG and DST root in the cabundle.. However the underlying TLS libraries on your system may fail to verify a cross signed certificate depending on the software and version, we made a release that excludes the expired cert.

I hope this resolves the issues you are seeing with our API service. 

Please let us know whether the shared solution resolved the issue for you.

**Comment by lahmacun** [comment]
Hi @rkoopmans ,
Thanks for quick reply. Unfortunately, I still getting the error even though I updated to cacert.pem file and cleared my application cache.
I can provide you any information that you need to solve this problem. I had to temporarely disable the image compression on my website. I hope we can solve this issue soon.

**Comment by rkoopmans** [comment]
Could you verify that the contents of your local cacert.pem and the one upstream (https://github.com/tinify/tinify-php/blob/master/lib/data/cacert.pem) 

In case it is, please share your php and openssl version so we can try to reproduce it.

**Comment by lahmacun** [comment]
Contents of the files are exactly the same.

`php -v`
```
PHP 7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0 (cli) (built: Feb  9 2019 06:51:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0, Copyright (c) 1999-2018, by Zend Technologies
```

`openssl version`
```
OpenSSL 1.1.0l  10 Sep 2019
```

`curl --version`
```
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by RemyMandon** [comment]
Hi lahmacun,

We are facing the same issue on our project. 
Here are our versions :

openssl version
OpenSSL 1.1.0j  20 Nov 2018

php -v
PHP 7.0.33 (cli) (built: Dec 29 2018 06:56:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.66.0~linux-x64-non_zts70, https://blackfire.io, by Blackfire

curl --version
curl 7.52.1 (x86_64-pc-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2q zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

Our content of cacert.perm are also identical

Thanks

**Comment by SD-Nathan** [comment]
Hi everyone,

We're encountering the very same issue. 
Cacert.pem is identical, and we're getting the very same errors : Error while connecting: SSL certificate problem: certificate has expired (#60).

**Comment by rkoopmans** [comment]
Hi,

I digged a bit deeper, and it seems that these versions of PHP are ignoring our certificate bundle and are using the system installed certificate bundles.

In my docker install with php:7.2.15-cli and php:7.0-cli I did the following steps to confirm:

$ rm /etc/ssl/certs/DST_Root_CA_X3.pem

and ran my tinify script and it successfully optimised various files.

Please update your operating systems, in particular the ca-certificates package. After updating ca-certificates, i did not have to remove the DST root manually.

**Comment by lahmacun** [comment]
Hi @rkoopmans,

Thank you, this solved the problem but I'm worrying about something. Is there any opportunity that this change may broke some other things?

**Comment by rkoopmans** [comment]
Hi Iahmacun,

Thank you for the feedback.

it is highly unlikely that this change broke other things. Most likely it has resolved more potential issues because any LetsEncrypt enabled website would fail with a certificate error due to the expired DST Root. There is a bug in older versions of TLS libraries that incorrectly mark the connection as insecure. 

The certificate is cross signed by ISRG Root and DST Root. DST expired, and even though you trust ISRG (which is still valid) the connection fails. Therefore removing the old expired DST Root solves the problem. On modern systems this is not a problem.

**Comment by rolecs** [comment]
> Hi,
> 
> I digged a bit deeper, and it seems that these versions of PHP are ignoring our certificate bundle and are using the system installed certificate bundles.
> 
> In my docker install with php:7.2.15-cli and php:7.0-cli I did the following steps to confirm:
> 
> $ rm /etc/ssl/certs/DST_Root_CA_X3.pem
> 
> and ran my tinify script and it successfully optimised various files.
> 
> Please update your operating systems, in particular the ca-certificates package. After updating ca-certificates, i did not have to remove the DST root manually.

Hello. My shared hosting does not allow deleting this file, are there any other options to solve the problem?

**Comment by RakhimErmatov** [comment]
I have the same problem. Replaced the file. Does not work

**Comment by rkoopmans** [comment]
Hi,

We changed our certificate chain, could you try connecting again? It should be resolved right now.

**Comment by RakhimErmatov** [comment]
> Hi,
> 
> We changed our certificate chain, could you try connecting again? It should be resolved right now.

Thanks. Works.
