### ISSUE TITLE
PHP 8.2: Deprecated ${} string interpolation.

### ISSUE THREAD

**Issue by kevin-appelt** [tinify/tinify-php#34]
> **`${var}` String Interpolation Deprecated**
> PHP has always supported string variable interpolation with `"foo {$bar}"` pattern, and along with an alternative syntax that the dollar sign is placed outside the curly braces (e.g. `"foo ${bar}"`).
> In PHP 8.2, the alternative syntax of placing the dollar sign outside the curly braces is deprecated.
> 
> Deprecated in PHP 8.2 | Recommended syntax for PHP 8.2
> -- | --
> Hello ${name}; | Hello {$name}
> echo "Hello ${$var}"; | echo "Hello {$var}";
Source: https://php.watch/versions/8.2

For detailed information see PHP RFC: https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation

**Comment by rkoopmans** [comment]
Thanks for your report, we have prepared a change!

**Comment by kevin-appelt** [comment]
@rkoopmans Thanks for the change. LGTM and I am looking forward for the release. :)

**Comment by kevin-appelt** [comment]
@rkoopmans AFAICS you merged the changes to master and changed the bumped the version in the code, but there is a tag missing to get the release f.e. via packagist.

Mind to add the 1.6.1 tag? :)

If done, this issues can be closed 👍
